version: '3'

services:
  # ---------------------------------
  # laravelを動かすコンテナ
  # ---------------------------------
  app:

    ports:
      - "2222:80"

    build: ./docker/app

    container_name: jp_app

    volumes:
      - ./src:/var/www/html
  # ----------------------------------
  # MySQLを動かすコンテナ
  # ----------------------------------
  db:

    image: mysql:8.0

    container_name: jp_db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jp_db
      MYSQL_USER: jp_user
      MYSQL_PASSWORD: jp_pass
      TZ: 'Asia/Tokyo'

    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

    ports:
      - 3306:3306
  # ----------------------------------
  # phpMyAdminを動かすコンテナ
  # ----------------------------------
  phpmyadmin:

    image: phpmyadmin/phpmyadmin:5

    container_name: phpmyadmin-jp

    links:
      - db

    ports:
      - 2223:80

    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  # ----------------------------------
  # MailCatcherを動かすコンテナ
  # ----------------------------------
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 2208:1080
